# used as an identifier to group runs and for wandbb logging group
experiment-name: no-augmentation

# yes / no
use-gpu: yes

model:
  type: autoencoder
  sub-type: RNN

  # specific to model-type and sub-type
  config:
    encoding-layers:
      - class-name: GRU
        arguments:
          units: 10
      - class-name: LeakyReLU
        arguments:
          alpha: 0.1
    decoding-layers:
      - class-name: GRU
        arguments:
          units: 10
          return_sequences: True
    optimizer:
      class-name: Adam
#      args:


autoencoder:
  latent-dim: 5
  # weight for Kullback-Leibler divergence in loss function
  kl-weight: 0.5
  epochs: 500
  batch-size: 1024

data:
  data-set: mit-bih
  location: /home/robin/Documents/lbnl/crd/RealDatasets/ANNOTATIONS/
  train-sets: [ 803 ]
  # define groups of ctu sets for testing. The model will be tested on all of these groups
  test-groups:
    all: [ 803, 805, 806, 820 ]
    #    train: [ 803, 806 ]
    803: [ 803 ]
#    805: [ 805 ]
#    806: [ 806 ]
#    820: [ 820 ]

preprocessing:
  # small, medium, large (see preprocessing.py)
  # list of noise, noise-replace, reverse, reverse-replace
  time-steps: 60
  augmentation: [ noise ]

downstream:
  #  tasks: [ best-fit-pdf]
  tasks: [ kde, best-fit-pdf ]

logging:
  log-location: ./runs
  #copies the preprocessed data to the run dir (the same data as the cached one)
  copy-data: false
  use-wandb: true


  wandb:
    project: ctu-13-augment-bih-803
    entity: lbl-crd
